// <auto-generated />
using EmployeeManagement.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EmployeeManagement.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20200616095705_AddPhoneNumberColumn")]
    partial class AddPhoneNumberColumn
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EmployeeManagement.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AvatarPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Department")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvatarPath = "~/images/nonavatar.png",
                            Department = 1,
                            Email = "khoa.nguyen@codegym.vn",
                            Name = "Khoa"
                        },
                        new
                        {
                            Id = 2,
                            AvatarPath = "~/images/nonavatar.png",
                            Department = 2,
                            Email = "khoa.nguyen@codegym.vn",
                            Name = "Phuc"
                        },
                        new
                        {
                            Id = 3,
                            AvatarPath = "~/images/nonavatar.png",
                            Department = 1,
                            Email = "khoa.nguyen@codegym.vn",
                            Name = "Khanh"
                        },
                        new
                        {
                            Id = 4,
                            AvatarPath = "~/images/nonavatar.png",
                            Department = 1,
                            Email = "hoang.phan@codegym.vn",
                            Name = "Hoang"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
